public enum EventKey
{
    NONE = -1,
    STARTGAME,
    ENDGAME,
    UPDATE_UI,
    SPAWNMERGEFRUIT,
    MERGEFRUIT,
    UPDATENEXTFRUITSPRITEHINT,
    ONTIMERGAMEOVER,
    OFFTIMERGAMEOVER,
    INCREASEFRUITCOUNT,
    DECREASEFRUITCOUNT,
    ADDSCORE,
    UPDATEHIGHTSCORE,
    OnChangeScore,
    OnChangeHighScore,
    OnToggleSound,
    DROPFRUITSOUND,

}